<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Slim 3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=no">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" type='text/css' />
    <link rel="stylesheet" href="/static/open-iconic-master/font/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.min.css">
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src='/static/bootstrap/js/bootstrap.min.js'></script>
    <script src="/static/vue.min.js"></script>
    <style>
        html {
            /* background: linear-gradient(45deg, #DE6262 10%, #FFB88C 90%);
            height: 100vh; */
        }

        body {
            background: url('/static/images/bg-mask.jpg') no-repeat right top white;
        }

        .nav {
            border-bottom: 2px solid #78C2AD;
            background: white;
            box-shadow: 0 2px 12px 4px rgba(0, 0, 0, .05);
        }

        /* .nav a{
            border-right: 1px solid #efefef;
        } */

        .nav a span.oi {
            font-size: 150%;
        }

        .nav a.active {
            border-radius: 0;
        }

        .nav a.active span.oi {
            /* color: #78C2AD; */
            color: white;
        }
    </style>
</head>

<body>
    <nav class="nav nav-pills nav-fill sticky-top">
        <a class="nav-item nav-link active" href="#">
            记录
            <br/>
            <span class="oi oi-list" title="icon name" aria-hidden="true"></span>
        </a>
        <a class="nav-item nav-link" href="/repository">
            库存
            <br>
            <span class="oi oi-beaker" title="icon name" aria-hidden="true"></span>
        </a>
        <a class="nav-item nav-link" href="/meta">
            花材
            <br>
            <span class="oi oi-lightbulb" title="icon name" aria-hidden="true"></span>
        </a>
        <a class="nav-item nav-link" href="#">
            报表
            <br>
            <span class="oi oi-bar-chart" title="icon name" aria-hidden="true"></span>
        </a>
    </nav>
    <div id="app">
        <div class="container mt-2 mb-2">
        <?php if(isset($msg)):?>
        <div class="alert alert-success" role="alert">
            <strong><?=implode('<br/>',$msg);?></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
        <?php endif;?>
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="#">记录</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">添加记录</li>
                </ol>
            </nav>
            <div class="tool mb-2">
                <a class="btn btn-info btn-sm" href='/list'>
                    <span class="oi oi-bookmark" title="icon name" aria-hidden="true"></span> 查看记录</a>
            </div>

            <hr>
            <h4 class='text-secondary'>
                花材清单
                <!-- <span class="badge badge-secondary">花材清单</span>      -->
            </h4>
            <!-- <div class="alert alert-dismissible alert-secondary">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Well done!</strong> 可以添加已经组合好的花束或者从批次中选择
            </div> -->
            <button type="button" class="btn btn-primary btn-sm mb-1" data-toggle="modal" data-target="#meta-dialog">
                <span class="oi oi-plus" title="icon name" aria-hidden="true"></span> 添加花材</button>
            <table class="table table-bordered table-sm">
                <thead>
                    <tr>
                        <th>批次</th>
                        <th scope="col">材料</th>
                        <th scope="col">数量</th>
                        <th scope="col">操作</th>
                    </tr>
                </thead>
                <tbody>
                    <tr v-for='item in listing_human'>
                        <th>{{item.flow|flow_id_map}}</th>
                        <td>{{item.meta|meta_id_map}}</td>
                        <td>{{item.count}}</td>
                        <td>
                            <a href='###'>
                                <span class="oi oi-pencil" title="icon name" aria-hidden="true"></span>
                            </a>
                            <a href='###' class="text-danger ml-2">
                                <span class="oi oi-x" title="icon name" aria-hidden="true"></span>
                            </a>
                        </td>
                    </tr>
                </tbody>
            </table>
            <hr>
            <form method='post'>
            <div class="form-group">
                    <label for="exampleInputPassword1">名称</label>
                    <div class='input-group'>
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <span class="oi oi-yen" title="icon name" aria-hidden="true"></span>
                            </div>
                        </div>
                        <input type="text" class="form-control" id="exampleInputPassword1" placeholder="花束名称" name='name' required>
                    </div>
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">金额</label>
                    <div class='input-group'>
                        <div class="input-group-prepend">
                            <div class="input-group-text">
                                <span class="oi oi-yen" title="icon name" aria-hidden="true"></span>
                            </div>
                        </div>
                        <input type="number" class="form-control" id="exampleInputPassword1" placeholder="type a number here" name='amount' required>
                    </div>
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small> -->
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">联系方式</label>
                    <input type="text" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="type here" name='concats'>
                </div>
                <div class="form-group">
                    <label for="remark">备注</label>
                    <textarea class="form-control" id="remark" aria-describedby="emailHelp" placeholder="type here" name='remark'></textarea>
                </div>
                <input type='hidden' name='formulas' v-model='formulas'/>
                <button type="submit" class="btn btn-primary">新增</button>
            </form>
        </div>


        <div id='meta-dialog' class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">花材属性</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h5>材料</h5>
                        <select name="" class='form-control' v-model='meta' @change='change'>
                            <option value="0" disabled>请选择花材</option>
                            <option v-for='meta in metas' v-bind:value='meta.id'>{{meta.name}}</option>
                        </select>                        
                        <hr>
                        <h5>批次</h5>
                        <select name="" id="" class='form-control' v-model='flow' v-bind:disabled='meta == 0'>
                            <option v-for='flow in flows' :value='flow.id'>{{flow.name}}-{{flow.created_at}}</option>
                        </select>
                        <small id="emailHelp" class="form-text text-muted">如果是空的表示库存不足,请先添加<a href='/repository'>库存</a></small>
                        <hr>
                        <h5>数量</h5>
                        <input type="number" class='form-control' v-model='count'>

                        <hr>
                        <button @click='push' class="btn btn-primary btn-sm">添加</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        var helper = {
            flow_id_map: function (items,val) {
                var item = items.find(item => {
                    return item.id == val
                })

                return item.created_at
            },
            meta_id_map: function (items,val) {
                var item = items.find(item => {
                    return item.id == val
                })
                return item.name
            }
        }
        var app = new Vue({
            el: '#app',
            data: {
                listing: [],
                listing_human:[],
                metas:<?= $metas;?>,
                formulas:[],
            flows: [],
            meta: 0,
            flow: 0,
            count: 1
        },
            methods: {
                change: function () {
                    var self = this
                    $.get('/repository/retrieval/' + this.meta).done(function (data) {
                        self.flows = JSON.parse(data)
                        self.flow = self.flows[0].id
                    }).fail(function () {

                    })
                },
                push: function (ev) {
                    this.listing.push({ meta: this.meta, flow: this.flow, count: this.count })
                    this.listing_human.push({ meta:helper.meta_id_map(this.metas,this.meta),flow:helper.flow_id_map(this.flows,this.flow),count:this.count})
                    this.flow = 0
                    this.count = 1
                    this.meta = 0
                    //this.flows = []    
                    this.formulas = JSON.stringify(this.listing)              

                    $('#meta-dialog').modal('hide')
                }
            }
        })
    </script>
</body>

</html>