<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <title>Slim 3</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0,user-scalable=no">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" type='text/css' />
    <link rel="stylesheet" href="/static/open-iconic-master/font/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.min.css">
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src='/static/bootstrap/js/bootstrap.min.js'></script>
    <!-- <script src="/static/vue.min.js"></script> -->
    <script src='/static/sweetalert2.all.min.js' type='text/javascript'></script>
    <style>
        html {
            /* background: linear-gradient(45deg, #DE6262 10%, #FFB88C 90%);
            height: 100vh; */
        }

        body {
            background: url('/static/images/bg-mask.jpg') no-repeat right top white;
        }

        .nav {
            border-bottom: 2px solid #78C2AD;
            background: white;
            box-shadow: 0 2px 12px 4px rgba(0, 0, 0, .05);
        }

        /* .nav a{
            border-right: 1px solid #efefef;
        } */

        .nav a span.oi {
            font-size: 150%;
        }

        .nav a.active {
            border-radius: 0;
        }

        .nav a.active span.oi {
            /* color: #78C2AD; */
            color: white;
        }
    </style>
</head>

<body>
    <nav class="nav nav-pills nav-fill sticky-top">
        <a class="nav-item nav-link active" href="#">
            记录
            <br/>
            <span class="oi oi-list" title="icon name" aria-hidden="true"></span>
        </a>
        <a class="nav-item nav-link" href="/repository">
            库存
            <br>
            <span class="oi oi-beaker" title="icon name" aria-hidden="true"></span>
        </a>
        <a class="nav-item nav-link" href="/meta">
            花材
            <br>
            <span class="oi oi-lightbulb" title="icon name" aria-hidden="true"></span>
        </a>
        <a class="nav-item nav-link" href="#">
            报表
            <br>
            <span class="oi oi-bar-chart" title="icon name" aria-hidden="true"></span>
        </a>
    </nav>
    <div id="app">
        <div class="container mt-2">
            <nav aria-label="breadcrumb">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item">
                        <a href="/">记录</a>
                    </li>
                    <li class="breadcrumb-item active" aria-current="page">记录列表</li>
                </ol>
            </nav>
            <div class="tool mb-2">
                <a class="btn btn-info btn-sm" href='/'>
                    <span class="oi oi-bookmark" title="icon name" aria-hidden="true"></span> 添加记录</a>
            </div>
            <hr>
            <!-- <div class="alert alert-dismissible alert-secondary">
                <button type="button" class="close" data-dismiss="alert">&times;</button>
                <strong>Well done!</strong> 可以添加已经组合好的花束或者从批次中选择
            </div> -->
            <table class="table">
                <tbody>
                    <tr>
                        <td>ID</td>
                        <td>名称</td>
                        <td>金额</td>
                        <td>详细</td>
                    </tr>
                    <?php while($row = $stm->fetch(PDO::FETCH_ASSOC)):?>
                    <tr>
                        <th scope="row">
                            <?=$row['id'];?>
                        </th>
                        <td>
                            <?=$row['name'];?>
                        </td>
                        <td>
                            <?=$row['amount'];?>
                        </td>
                        <td>
                            <button class='btn btn-primary btn-sm' data-detail='<?=$row['id'];?>'>查看</button>
                        </td>
                    </tr>
                    <?php endwhile;?>
                </tbody>
            </table>
        </div>


        <div id='meta-dialog' class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel"
            aria-hidden="true">
            <div class="modal-dialog modal-lg">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">花材属性</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <h5>材料</h5>
                        <select name="" class='form-control' v-model='meta' @change='change'>
                            <option value="0" disabled>请选择花材</option>
                            <option v-for='meta in metas' v-bind:value='meta.id'>{{meta.name}}</option>
                        </select>
                        <hr>
                        <h5>批次</h5>
                        <select name="" id="" class='form-control' v-model='flow' v-bind:disabled='meta == 0'>
                            <option v-for='flow in flows' :value='flow.id'>{{flow.name}}-{{flow.created_at}}</option>
                        </select>
                        <small id="emailHelp" class="form-text text-muted">如果是空的表示库存不足,请先添加
                            <a href='/repository'>库存</a>
                        </small>
                        <hr>
                        <h5>数量</h5>
                        <input type="number" class='form-control' v-model='count'>

                        <hr>
                        <button @click='push' class="btn btn-primary btn-sm">添加</button>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script type='text/javascript'>
        $('[data-detail]').on('click', function () {
            var id = $(this).data('detail')
            var ipAPI = '/formula/detail/' + id
            $.get(ipAPI).then(data=>{
                var str = `
                            <table class='table'>
                                <tr>
                                    <td>金额</td>
                                    <td>${data.meta.amount}</td>
                                    </tr>
                                    <tr>
                                    <td>联系人</td>
                                    <td>${data.meta.concats}</td>
                                    </tr>
                                    <tr>
                                    <td>创建日期</td>
                                    <td>${data.meta.created_at}</td>
                                    </tr>
                                    <tr>
                                    <td>备注</td>
                                    <td>${data.meta.remark}</td>
                                    </tr>
                                </table>
                                <h3>配方</h3>
                                <table class='table'>
`;
                            if('formulas' in data){
                                data.formulas.forEach(item=>{
                                    str +='<tr><td>花材</td><td>'+item.name+'</td></tr>'
                                    str +='<tr><td>费用</td><td>'+item.amount+'</td></tr>'
                                    str +='<tr><td>数量</td><td>'+item.count+'</td></tr>'
                                })
                            }
                            
                swal({
                    title:'清单',
                    html:str
                })
            }).catch(err=>{
                swal('error','please try again later','error')
            })
        })
    </script>
</body>

</html>