<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="stylesheet" href="/static/bootstrap/css/bootstrap.min.css" type='text/css' />
    <link rel="stylesheet" href="/static/open-iconic-master/font/css/open-iconic-bootstrap.min.css">
    <link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.min.css">
    <script src='/static/sweetalert2.all.min.js' type='text/javascript'></script>
    <title>Signin for Simu store</title>
    <style>
    html,
body {
  height: 100%;
}

body {
  display: -ms-flexbox;
  display: -webkit-box;
  display: flex;
  -ms-flex-align: center;
  -ms-flex-pack: center;
  -webkit-box-align: center;
  align-items: center;
  -webkit-box-pack: center;
  justify-content: center;
  padding-top: 40px;
  padding-bottom: 40px;
  background-color: #f5f5f5;
}

.form-signin {
  width: 100%;
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin .checkbox {
  font-weight: 400;
}
.form-signin .form-control {
  position: relative;
  box-sizing: border-box;
  height: auto;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
    </style>
  </head>

  <body class="text-center">  
    <form class="form-signin" method='post'>
    <?php if(isset($msg)):?>
        <div class="alert alert-danger" role="alert">
            <strong><?=implode('<br/>',$msg);?></strong>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
        </div>
        <?php endif;?>
      <!-- <img class="mb-4" src="https://getbootstrap.com/assets/brand/bootstrap-solid.svg" alt="" width="72" height="72"> -->
      <span class="oi oi-sun" title="icon name" aria-hidden="true" style='font-size: 6em;color: #ffce67;'></span>
      <h1 class="h3 mb-3 font-weight-normal">登陆</h1>
      <label for="inputEmail" class="sr-only">User name</label>
      <input type="text" id="inputEmail" class="form-control" placeholder="User name" required autofocus name='username'>
      <label for="inputPassword" class="sr-only">Password</label>
      <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name='password'>
      <div class="checkbox mb-3">
        <label>
          <input type="checkbox" value="1" name='remember'> Remember me
        </label>
      </div>
      <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      <p class="mt-5 mb-3 text-muted">&copy; 2017-2018</p>
    </form>

    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdn.bootcss.com/popper.js/1.12.9/umd/popper.min.js"></script>
    <script src='/static/bootstrap/js/bootstrap.min.js'></script>

    <script>
        $(function(){
            $(document.forms[0]).submit(function(){
                $.post('/login',$(this).serialize()).then(function(data){
                    if(data.status){
                        swal('提示',data.msg,'success').then(()=>{
                            window.location.href='/'
                        });
                    }else{
                        swal('提示',data.msg,'error')
                    }
                }).catch(function(){
                    swal('Error','Please try again late');
                })

                return false;
            })
        })
    </script>
  </body>
</html>